import type { NextPage } from "next";
import Head from "next/head";
import styled from "@emotion/styled";
import { PurchaseHistoryCont } from "../../components/PurchaseHistory/CardContainer";
import { WishListContainer } from "../../components/WishList/CardContainer";

const MyPage: NextPage = () => {
  return (
    <section>
      <Head>
        <title>마이 페이지</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MyPageCont>
        <PageTitle>마이 페이지</PageTitle>
        <PurchaseHistoryCont />
        <WishListContainer />
      </MyPageCont>
    </section>
  );
};

const MyPageCont = styled.main`
  padding: 0px 96px;
`;

const PageTitle = styled.h1`
  font-size: 2.4rem;
  font-weight: 700;
  margin-bottom: 72px;
`;

export default MyPage;
