import styled from "@emotion/styled";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import StarFilled from "../../../public/assets/star_filled.png";
import StarOutlined from "../../../public/assets/star_outlined.png";

const ReviewPage: NextPage = () => {
  return (
    <div>
      <Head>
        <title>리뷰 작성</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <Title>마이 페이지</Title>
        <ReviewContainer>
          <ReviewTitle>리뷰작성</ReviewTitle>
          <Content>
            <ImgContent>
              <ImgContainer></ImgContainer>
              <AddImgBtn>이미지 추가</AddImgBtn>
            </ImgContent>
            <UserReviewContainer>
              <Text>별점 및 리뷰</Text>
              <StarContainter>
                <Image src={StarFilled} alt="별점" width={22} height={22} />
                <Image src={StarFilled} alt="별점" width={22} height={22} />
                <Image src={StarFilled} alt="별점" width={22} height={22} />
                <Image src={StarOutlined} alt="별점" width={22} height={22} />
                <Image src={StarOutlined} alt="별점" width={22} height={22} />
              </StarContainter>
              <ReviewInput
                rows={8}
                cols={80}
                placeholder="상품에 대한 솔직한 리뷰를 작성해주세요."
              ></ReviewInput>
              <ReviewSubmitBtn type="submit">등록하기</ReviewSubmitBtn>
            </UserReviewContainer>
          </Content>
        </ReviewContainer>
      </Container>
    </div>
  );
};

const Container = styled.div`
  padding: 72px 72px 0px 72px;
`;

const Title = styled.h1`
  font-weight: 700;
  font-size: 2.4rem;
  color: #000000;
  margin-bottom: 72px;
`;

const ReviewContainer = styled.section`
  display: flex;
  flex-direction: column;
`;

const ReviewTitle = styled.h1`
  font-weight: 700;
  font-size: 2.4rem;
  color: #000000;
  margin-bottom: 72px;
`;

const Content = styled.div`
  display: flex;
`;

const ImgContent = styled.div`
  width: fit-content;
  position: relative;
  margin-right: 60px;
`;

const ImgContainer = styled.div`
  width: 241px;
  height: 241px;
  background-color: #c4c4c4;
  margin-bottom: 15px;
`;

const AddImgBtn = styled.button`
  background-color: #e5e5e5;
  color: #666666;
  font-weight: 700;
  font-size: 1.8rem;
  border-radius: 10px;
  padding: 5px 20px;
  position: absolute;
  right: 0;
`;

const UserReviewContainer = styled.div`
  position: relative;
`;

const Text = styled.p`
  font-weight: 700;
  font-size: 2rem;
  color: #000000;
  margin-bottom: 22px;
`;

const StarContainter = styled.div`
  margin-bottom: 22px;
`;

const ReviewInput = styled.textarea`
  margin-bottom: 76px;
  overflow: hidden;
  padding: 8px 16px;
  font-size: 1.8rem;
  outline-color: none;
  resize: none;
  &:focus {
    outline: none;
  }
`;

const ReviewSubmitBtn = styled.button`
  background-color: #847258;
  font-size: 2rem;
  width: 280px;
  height: 50px;
  border-radius: 10px;
  color: #ffffff;
  position: absolute;
  bottom: -76px;
  left: 25%;
`;

export default ReviewPage;
